// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HomeApi222Data, HomeApi222Responses, HomeDocData, HomeDocResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 首页文档
 *
 * 首页文档:undefined
 */
export const homeDoc = <ThrowOnError extends boolean = false>(options: Options<HomeDocData, ThrowOnError>) => (options.client ?? client).get<HomeDocResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * 首页文档
 *
 * 首页文档:undefined
 */
export const homeApi222 = <ThrowOnError extends boolean = false>(options: Options<HomeApi222Data, ThrowOnError>) => (options.client ?? client).get<HomeApi222Responses, unknown, ThrowOnError>({
    url: '/api222',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
