// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type InfoFile = {
    /**
     * url
     */
    url: string;
    /**
     * 文件名称
     */
    file_name: string;
};

export type Login = {
    /**
     * 手机号
     */
    phone: string;
    /**
     * 密码
     */
    password: string;
    /**
     * 验证码
     */
    code: string;
    /**
     * 列表-主图轮播图
     */
    list_img: Array<InfoFile>;
};

export type HomeDocData = {
    body?: never;
    headers: {
        /**
         * token
         */
        token: string;
    };
    path?: never;
    query?: never;
    url: '/';
};

export type HomeDocResponses = {
    200: unknown;
};

export type HomeApi222Data = {
    body: Login;
    headers: {
        /**
         * token
         */
        token: string;
    };
    path?: never;
    query?: never;
    url: '/api222';
};

export type HomeApi222Responses = {
    200: unknown;
};
